apiVersion: v1
kind: ConfigMap
metadata:
  name: recommender-config
  namespace: gabrielmartins
data:
  dataset_path: "/home/datasets/spotify/2023_spotify_ds1.csv"
  model_path: "/mnt/model/model.pkl"
  ml_image_tag: "0.4"
  frontend_image_tag: "0.4"
