apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: gabrielmartins
spec:
  selector:
    app: frontend-recommender
  ports:
    - protocol: TCP
      port: 50011
      targetPort: 5000
  type: ClusterIP
